export const posts = [
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-1.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/aatrox/',
        date: '10-01-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-2.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/akali/',
        date: '21-03-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-3.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/aphelios/',
        date: '02-04-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-4.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/ashe/',
        date: '26-11-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-5.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/azir/',
        date: '13-12-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-6.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/brand/',
        date: '17-01-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-7.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/chogath/',
        date: '29-08-1993',
        author: 'admin',
        commentsCount: '2',
    },
    {
        name: "Amazing Image Post",
        img: 'img/breaking-news-img/break-news-8.png',
        link: 'https://universe.leagueoflegends.com/en_US/story/champion/galio/',
        date: '30-09-1993',
        author: 'admin',
        commentsCount: '2',
    },
    // {
    //     name: "Amazing Image Post",
    //     img: 'img/breaking-news-img/break-news-7.png',
    //     link: 'https://universe.leagueoflegends.com/en_US/story/champion/chogath/',
    //     date: '11-11-1993',
    //     author: 'admin',
    //     commentsCount: '2',
    // },
    // {
    //     name: "Amazing Image Post",
    //     img: 'img/breaking-news-img/break-news-8.png',
    //     link: 'https://universe.leagueoflegends.com/en_US/story/champion/galio/',
    //     date: '30-12-1993',
    //     author: 'admin',
    //     commentsCount: '2',
    // },

]